### ISSUE TITLE
CLI showing a ton of altitudes errors

### ISSUE THREAD

**Issue by nickmhc** [MonkeyTedBaker/Monocle#20]
I'm assuming it isn't really an issue and is just related to the same old Google Elevation API limits, but figured I'd post anyways

```During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nmc/github/mtb1/monocle/altitudes.py", line 76, in fetch
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.5/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nmc/github/mtb1/scan.log'
Call stack:
  File "scan.py", line 223, in <module>
    main()
  File "scan.py", line 215, in main
    LOOP.run_until_complete(launcher)
  File "/home/nmc/github/mtb1/monocle/overseer.py", line 515, in try_point
  File "/home/nmc/github/mtb1/monocle/worker.py", line 665, in visit
  File "/home/nmc/github/mtb1/monocle/altitudes.py", line 84, in fetch
  File "/usr/lib/python3.5/logging/__init__.py", line 1619, in error
    self.log(ERROR, msg, *args, **kwargs)
  File "/home/nmc/github/mtb1/monocle/shared.py", line 56, in log
Message: <monocle.shared.Message object at 0x7fe95822d470>
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/nmc/github/mtb1/monocle/worker.py", line 663, in visit
  File "/home/nmc/github/mtb1/monocle/altitudes.py", line 62, in get
KeyError: (34.0446, -118.5078)
```

**Comment by nickmhc** [comment]
I might add that I have two other instances that aren't spazzing out with these errors every 0.25 seconds... It isn't affecting the performance of the instance, just looks like it's freaking out

**Comment by evilmoses** [comment]
Just remove your google api key from config and you won't get them any more....

**Comment by MonkeyTedBaker** [comment]
As evil moses said, this is a non-issue. Your other two instances are fine because, they have all the altitude data needed already saved in altitudes.pickle.

**Comment by MonkeyTedBaker** [comment]
Can you pls close this issue if unnecessary?
